name: Main

on: push

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get trunk
        uses: jetli/trunk-action@v0.5.0
      - name: Add WASM
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: trunk build --release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 
            dist/index.html